### ISSUE TITLE
Issue for article 'Portable file path operations'

### ISSUE THREAD

**Issue by fg-dev** [essentialbooks/books#2]
From URL: https://www.programming-books.io/essential/go/a-rd6000ld-portable-file-path-operations
File: https://github.com/essentialbooks/books/blob/master/books/go/0250-file-io/050-filepath.md

in section  

> Get file extension

`path := filepath.Join("dir", "file.txt")`
`ext := filepath.Dir(path)`
`// ext = ".txt" `

the correct function is 
`ext := filepath.Ext(path)`

**Comment by kjk** [comment]
Fixed, thanks!
