### ISSUE TITLE
Deferred Function Arguments "gotcha" is incorrect

### ISSUE THREAD

**Issue by russoj88** [essentialbooks/books#32]
https://www.programming-books.io/essential/go/130-defer-gotchas#deferred-function-arguments

The gotcha or issue shown here does not only happen with defer.  It's happening because it is using the for loop variable.  I think this is misleading to put it under a defer gotcha.

The following code will also generate expected output:
```go
for i := 0; i < 2; i++ {
	i2 := i
	defer func() {
		fmt.Printf("%d\n", i2)
	}()
}
```

**Comment by kjk** [comment]
This is not actionable. I don't know what you propose to do.

Remove that part? It is a chapter about defer statement and it is an issue that people run into while using deferred statement.

Clarify the wording? You can submit a change https://github.com/essentialbooks/books/edit/master/books/go/0190-defer/020-defer-gotchas.md

**Comment by russoj88** [comment]
As I said, it's not just an issue with defer, which is the misleading part.  People also run into the same issue with for loops calling any functions.

https://golang.org/doc/faq#closures_and_goroutines

I think mentioning that it is a result of the for loop variable would be good.

**Comment by kjk** [comment]
I don't know how  "mention it's a result of the for loop variable" translates into making an actual change to the text.

Like I said, if you have a specific clarification in mind, then submit a change.

There's already a section where I try to explain why this happens and one way of fixing it.
