### ISSUE TITLE
Mobile View: while in one chapter, the column selection shows it's in the next.

### ISSUE THREAD

**Issue by texasbruce** [essentialbooks/books#34]
For example, while I am viewing Essential Go - Panic and Recover chapter, the column in the bottom shows I am in Concurrency, and I cannot select Concurrency chapter to go there.

There is no Next or Previous to navigate either.

**Comment by kjk** [comment]
Just to confirm: the issue is that we're in "Panic and recover" chapter but showing "Concurrency" as current?

Will fix, looks like off-by-one bug introduced recently.

**Comment by texasbruce** [comment]
@kjk That's an example. It actually happens to all chapters
